/***********************************************************************************************************************
 * This file was generated by the S32 Configuration Tools. Any manual edits made to this file
 * will be overwritten if the respective S32 Configuration Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v11.0
processor: S32K144
package_id: S32K144_LQFP100
mcu_data: s32sdk_s32k1xx_rtm_401
processor_version: 0.0.0
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: a6d43dcb-893a-49cd-9d9d-0bb26ff0f05b
  called_from_default_init: true
  selectedCore: core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/*******************************************************************************
 * Included files 
 ******************************************************************************/
#include "peripherals_trgmux1.h"

/*******************************************************************************
 * trgmux1 initialization code
 ******************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'trgmux1'
- type: 'trgmux_config'
- mode: 'general'
- custom_name_enabled: 'true'
- type_id: 'trgmux'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'TRGMUX'
- config_sets:
  - trgmux:
    - trgmuxCfg:
      - 0:
        - name: 'trgmux1_InitConfig0'
        - readonly: 'true'
        - mapping_cfg:
          - 0:
            - triggerSource: 'TRGMUX_TRIG_SOURCE_FTM0_INIT_TRIG'
            - targetModule: 'TRGMUX_TARGET_MODULE_FTM3_HWTRIG0'
            - lockreg: 'false'
          - 1:
            - triggerSource: 'TRGMUX_TRIG_SOURCE_FTM3_INIT_TRIG'
            - targetModule: 'TRGMUX_TARGET_MODULE_PDB0_TRG_IN'
            - lockreg: 'false'
          - 2:
            - triggerSource: 'TRGMUX_TRIG_SOURCE_FTM3_INIT_TRIG'
            - targetModule: 'TRGMUX_TARGET_MODULE_PDB1_TRG_IN'
            - lockreg: 'false'
          - 3:
            - triggerSource: 'TRGMUX_TRIG_SOURCE_FTM3_INIT_TRIG'
            - targetModule: 'TRGMUX_TARGET_MODULE_TRGMUX_OUT2'
            - lockreg: 'false'
          - 4:
            - triggerSource: 'TRGMUX_TRIG_SOURCE_PDB1_CH0_TRIG'
            - targetModule: 'TRGMUX_TARGET_MODULE_TRGMUX_OUT3'
            - lockreg: 'false'
          - 5:
            - triggerSource: 'TRGMUX_TRIG_SOURCE_ADC1_SC1A_COCO'
            - targetModule: 'TRGMUX_TARGET_MODULE_TRGMUX_OUT6'
            - lockreg: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files in application code.
 *
 */
const trgmux_inout_mapping_config_t trgmux_InOutMappingConfig0[TRGMUX_NUM_IN_OUT_MAPPING_CONFIGS0] =
{
    {TRGMUX_TRIG_SOURCE_FTM0_INIT_TRIG, TRGMUX_TARGET_MODULE_FTM3_HWTRIG0, false},
    {TRGMUX_TRIG_SOURCE_FTM3_INIT_TRIG, TRGMUX_TARGET_MODULE_PDB0_TRG_IN, false},
    {TRGMUX_TRIG_SOURCE_FTM3_INIT_TRIG, TRGMUX_TARGET_MODULE_PDB1_TRG_IN, false},
    {TRGMUX_TRIG_SOURCE_FTM3_INIT_TRIG, TRGMUX_TARGET_MODULE_TRGMUX_OUT2, false},
    {TRGMUX_TRIG_SOURCE_PDB1_CH0_TRIG, TRGMUX_TARGET_MODULE_TRGMUX_OUT3, false},
    {TRGMUX_TRIG_SOURCE_ADC1_SC1A_COCO, TRGMUX_TARGET_MODULE_TRGMUX_OUT6, false},
};


/*! trgmux configuration structure */
const trgmux_user_config_t trgmux1_InitConfig0 = {
    .numInOutMappingConfigs = TRGMUX_NUM_IN_OUT_MAPPING_CONFIGS0,
    .inOutMappingConfig     = trgmux_InOutMappingConfig0,
};



